# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kb2dHkB4OadwwHrM4CFLntWspLeCOEMN
"""

import numpy as np
import pandas as pd
df = pd.read_csv('/content/titanic.csv')
df.head()

inputs = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Fare','Cabin','Embarked','Survived'], axis='columns')
target = df['Survived']
inputs

target

from sklearn.preprocessing import LabelEncoder
le_Pclass = LabelEncoder()
le_Sex = LabelEncoder()
le_age = LabelEncoder()

inputs['le_Pclass'] = le_Pclass.fit_transform(inputs['Pclass'])
inputs['le_Sex'] = le_Sex.fit_transform(inputs['Sex'])

inputs

inputs_n = inputs.drop(['Pclass','Sex','Age'],axis='columns')
inputs_n

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10)
model.fit(inputs_n,target)

model.score(inputs_n,target)

model.predict([[2,0]])

model.predict([[0,0]])